name: Manually trigger ML Prod job

on:
  workflow_dispatch:

jobs:
  prod-train:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      ENVIRONMENT: ${{vars.ENVIRONMENT}}

    steps:
      - name: Show Enviroment var env
        run: echo "Environment is $ENVIRONMENT "
      - name: Show Enviroment vars.ENVIRONMENT
        run: echo "Environment is ${{ vars.ENVIRONMENT }}"
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Trigger Azure Machine Learning job
        run: az ml job create --file src/job-prod.yml --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE }} -s
        #run: exit 1 #Force an error
      - name: Failed Job
        if: ${{failure()}}
        run: echo "Job Failed"
