name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    environment: Dev
    env:
      ENVIRONMENT: ${{vars.ENVIRONMENT}}
      
    steps:
    - name: Show Enviroment var env:
      run: echo "Environment is $ENVIRONMENT "
    - name: Show Enviroment vars.ENVIRONMENT
      run: echo "Environment is ${{ vars.ENVIRONMENT }}"
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}


