name: Manually trigger ML Prod job

on:
  workflow_dispatch:

jobs:
  prod-train:
    runs-on: ubuntu-latest
    environment: Prod
    env:
      ENVIRONMENT: ${{vars.ENVIRONMENT}}

    steps:
      - name: Show Enviroment var env
        run: echo "Environment is $ENVIRONMENT "
      - name: Show Enviroment vars.ENVIRONMENT
        run: echo "Environment is ${{ vars.ENVIRONMENT }}"
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Get the Job
        id: Job
        run: jobname=$(az ml job list --query "sort_by([?experiment_name=='diabetes-prod'].{Name:name,Jobstatus:status,Experiment:experiment_name,Created:creation_context.created_at}, &Created) | [-1].{JobName:Name}" -g rg-mlops-challenge  -w mlw-mlops-challenge -otsv)
             echo "::set-output name=jobname::$jobname"
      - name: Create End Point
        run: az ml online-endpoint create -f 20-RegisterModel/CreateEndPoint.yml --resource-group ${{ vars.RESOURCE_GROUP }} --workspace-name ${{ vars.WORKSPACE }}
      - name: Register model
        run: az ml model create --name diabetes-prod --path azureml://jobs/diabetes-prod/outputs/artifacts/paths/outputs --type mlflow_model 
      - name: Deploy model to an end point
        run: az ml online-deployment create -f .\20-RegisterModel\DeployModel.yml --all-traffic -g rg-mlops-challenge -w mlw-mlops-challenge
      - name: Test EndPoint
        run:  az ml online-endpoint invoke --name diabetes-mlflow --request-file ./20-TestEndPoint/Test_1.json